### ISSUE TITLE
`calculateItemWorth()` still not handling items / children without `upd`

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/server#206]
## **General information**
**Project issue is for:**
Server

**Expected result**:
Items with children without upd should be able to be have their tax calculated

**Actual result**:
Error

```
TypeError: Cannot use 'in' operator to search for 'Dogtag' in undefined
TypeError: Cannot use 'in' operator to search for 'Dogtag' in undefined
    at RagfairTaxService.calculateItemWorth (C:\snapshot\src\services\RagfairTaxService.ts:139:13)
    at RagfairTaxService.calculateItemWorth (C:\snapshot\src\services\RagfairTaxService.ts:128:35)
    at RagfairTaxService.calculateTax (C:\snapshot\src\services\RagfairTaxService.ts:65:32)
    at RagfairController.chargePlayerTaxFee (C:\snapshot\src\controllers\RagfairController.ts:741:38)
    at RagfairController.createSingleOffer (C:\snapshot\src\controllers\RagfairController.ts:463:45)
    at RagfairController.addPlayerOffer (C:\snapshot\src\controllers\RagfairController.ts:392:29)
    at RagfairCallbacks.addOffer (C:\snapshot\src\callbacks\RagfairCallbacks.ts:88:39)
    at RagfairItemEventRouter.handleItemEvent (C:\snapshot\src\routers\item_events\RagfairItemEventRouter.ts:29:46)
    at ItemEventRouter.handleEvents (C:\snapshot\src\routers\ItemEventRouter.ts:36:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot use 'in' operator to search for 'Dogtag' in undefined
TypeError: Cannot use 'in' operator to search for 'Dogtag' in undefined
    at RagfairTaxService.calculateItemWorth (C:\snapshot\src\services\RagfairTaxService.ts:139:13)
    at RagfairTaxService.calculateItemWorth (C:\snapshot\src\services\RagfairTaxService.ts:128:35)
    at RagfairTaxService.calculateTax (C:\snapshot\src\services\RagfairTaxService.ts:65:32)
    at RagfairController.chargePlayerTaxFee (C:\snapshot\src\controllers\RagfairController.ts:741:38)
    at RagfairController.createSingleOffer (C:\snapshot\src\controllers\RagfairController.ts:463:45)
    at RagfairController.addPlayerOffer (C:\snapshot\src\controllers\RagfairController.ts:392:29)
    at RagfairCallbacks.addOffer (C:\snapshot\src\callbacks\RagfairCallbacks.ts:88:39)
    at RagfairItemEventRouter.handleItemEvent (C:\snapshot\src\routers\item_events\RagfairItemEventRouter.ts:29:46)
    at ItemEventRouter.handleEvents (C:\snapshot\src\routers\ItemEventRouter.ts:36:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The fix applied here 

https://dev.sp-tarkov.com/SPT/Server/src/tag/3.9.6/project/src/services/RagfairTaxService.ts#L131
```
child.upd?.StackObjectsCount ?? 1,
```

Now fails in the following lines for the same reason

https://dev.sp-tarkov.com/SPT/Server/src/tag/3.9.6/project/src/services/RagfairTaxService.ts#L139-L173

Since the method will try to calculate the tax of the children recursively, and these children might not have `upd`

https://dev.sp-tarkov.com/SPT/Server/src/tag/3.9.6/project/src/services/RagfairTaxService.ts#L128-L134
```
worth += this.calculateItemWorth(
  child,
  this.itemHelper.getItem(child._tpl)[1],
  child.upd?.StackObjectsCount ?? 1,  
  pmcData,
  false,
);
```

## **Log files**
Server: Attached
BepinEx: Attached
Client: See next comment for traces

## **Profile**
You can optionally include your game profile if you think it would help us reproduce the error easily 
See next comment for profile

---
### Attachments
- [server-2024-08-17.log](https://dev.sp-tarkov.com/attachments/b31a4367-647a-4d72-b4a2-80ef813b94be) (2482 KiB)
- [LogOutput.log](https://dev.sp-tarkov.com/attachments/7f876f7e-4796-423c-99e8-3a80bcf75977) (140 KiB)

---

[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/749) by _**blacky**_

**Comment by refringe** [comment]
Profile and traces here

---
### Attachments
- [2024.08.17_21-38-16_0.14.9.1.30626 traces.log](https://dev.sp-tarkov.com/attachments/83f08540-5919-42e7-95d4-1141578c75ef) (114 KiB)
- [669401180002b97546c7ccd0.json](https://dev.sp-tarkov.com/attachments/f3bf044d-10ab-4496-bcb9-7b42d2263e82) (3578 KiB)


---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/749#issuecomment-27571) by _**blacky**_

**Comment by refringe** [comment]
It is not clear to me how to properly obtain items without `upd`, it just happens naturally through insurance sometimes (this affects vanilla weapons not modified by any mod and bought through the traders) and 100% with gear spawned in bots from mods (like realism or alb)

In the linked profile there is an AK in the stash where if this method is invoked it will fail; 100% reproducible with lootvalue quick sell

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/749#issuecomment-27572) by _**blacky**_

**Comment by refringe** [comment]
Simple unit test to verify behaviour

```
(() => {

    // given object without inner object
    const given = {
        
    };

    // when trying to use 'in' operator of non existing inner object
    const actual = (() => {

        try {
            "any" in given?.non_existing;
        } catch(error) {
            console.log(error);
            return error;
        }
        
    })();

    // then should be error
    return actual instanceof TypeError && 
        actual.message == `Cannot use 'in' operator to search for 'any' in undefined`; 
    
})();
    
```

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/749#issuecomment-27573) by _**blacky**_

**Comment by refringe** [comment]
Thank you for the investigation, it's tricky to replicate as the calculateTax() function is only called when a client-retrieved tax value isn't found, which should be never! 
The only way i can think of is via mods that call this function for their own purpose.

I've added some code to hopefully fix the issue: 
We clone the children and add a upd object to all of them (we clone to prevent the underlying data being modified in a function just for calculating tax) https://github.com/sp-tarkov/server/commit/fd50ec4ad82c5f984dabb4ffd4b3d22b270d58ba

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/749#issuecomment-27574) by _**chomp**_

**Comment by refringe** [comment]
Hey! Thanks for the fix, i was hestitant to report this before because as you said, this is mostly a mod issue and this issue cannot be replicated by using the actual UI to list on the flea market; but since you actually added a fix on the latest issue i took it as accepted! :)

I actually had a "patch" that replaced this function and did exactly as you fixed it, just adding an empty `upd` if the object didn't have any!

Thanks for your time 👍

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/749#issuecomment-27579) by _**blacky**_
