### ISSUE TITLE
3.9.0 - Loot generation can throw an exception due to filtering loot

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/server#234]
Had a user come into support with the following error:
```[2024-07-07T16:53:44.495Z] error: 	Error: Item for tpl 175862440 was not found in the spawn point
    at LocationGenerator.createDynamicLootItem (C:\snapshot\src\generators\LocationGenerator.ts:877:19)
    at LocationGenerator.generateDynamicLoot (C:\snapshot\src\generators\LocationGenerator.ts:745:43)
    at LocationController.generate (C:\snapshot\src\controllers\LocationController.ts:112:81)
    at LocationController.get (C:\snapshot\src\controllers\LocationController.ts:71:21)
    at LocationCallbacks.getLocation (C:\snapshot\src\callbacks\LocationCallbacks.ts:36:66)```

Looks to be a bug in the loot generation filtering in LocationGenerator.ts, around line 708. The `spawnPoint.template.Items` property is being filtered by blacklisted and event items, however no change is made to `spawnPoint.itemDistribution` to account for the removed items. This can cause an item to be picked from the itemDistribution that has been removed from Items, leading to this error

---

[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/721) by _**DrakiaXYZ**_

**Comment by refringe** [comment]
Looks like we can filter `itemDistribution` in the for loop slightly below those filters, that builds `itemArray`

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/721#issuecomment-27005) by _**DrakiaXYZ**_

**Comment by refringe** [comment]
Fixed: https://github.com/sp-tarkov/server/commit/7497f0d40f22af87766640b9da98287a9fe7b852

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/721#issuecomment-27006) by _**chomp**_
