### ISSUE TITLE
(Presets) Presets lead to fullProfile.Items is not iterable on Server.exe

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/server#391]
## **General information**
**Project issue is for:**
```
[2024-03-10T11:22:21.133Z] info: 	Commit hash: 1326ee962646512f904f739a626ebe275c4b425f
[2024-03-10T11:22:21.133Z] info: 	Build date: 1710025799471
[2024-03-10T11:22:21.265Z] info: 	Server: Startprozesse werden ausgeführt...
[2024-03-10T11:22:21.266Z] debug: 	OS: x64 | Windows 11 Home | win32
[2024-03-10T11:22:21.267Z] debug: 	CPU: AMD Ryzen 7 5800X 8-Core Processor              cores: 16
[2024-03-10T11:22:21.267Z] debug: 	RAM: 63.92GB
[2024-03-10T11:22:21.267Z] debug: 	PATH: RTpcU1BUIEFLSSAzODBcQWtpLlNlcnZlci5leGU=
[2024-03-10T11:22:21.267Z] debug: 	PATH: RTpcU1BUIEFLSSAzODBcQWtpLlNlcnZlci5leGU=
[2024-03-10T11:22:21.267Z] debug: 	Server: 3.8.0
[2024-03-10T11:22:21.267Z] debug: 	Date: 1710025799471
[2024-03-10T11:22:21.268Z] debug: 	Commit: 1326ee962646512f904f739a626ebe275c4b425f
```

**Expected result**:
Game to start

**Actual result**:
Game doesn't start, but hangs on a screen before loading and showing error message.
In the server the following message appears:
```
[2024-03-10T11:41:20.186Z] error: 	TypeError: fullProfile.userbuilds.weaponBuilds[buildId].Items is not iterable
[2024-03-10T11:41:20.185Z] debug: 	Started game with sessionId: 65bfbc370004e2f7515b406b ObiOne
[2024-03-10T11:41:20.186Z] error: 	TypeError: fullProfile.userbuilds.weaponBuilds[buildId].Items is not iterable
[2024-03-10T11:41:20.186Z] error: 	TypeError: fullProfile.userbuilds.weaponBuilds[buildId].Items is not iterable
    at ProfileFixerService.checkForOrphanedModdedItems (C:\snapshot\project\src\services\ProfileFixerService.ts:898:77)
    at GameController.gameStart (C:\snapshot\project\src\controllers\GameController.ts:189:42)
    at GameCallbacks.gameStart (C:\snapshot\project\src\callbacks\GameCallbacks.ts:62:29)
    at RouteAction.action (C:\snapshot\project\src\routers\static\GameStaticRouter.ts:36:43)
    at GameStaticRouter.handleStatic (C:\snapshot\project\src\di\Router.ts:47:63)
    at HttpRouter.handleRoute (C:\snapshot\project\src\routers\HttpRouter.ts:79:62)
    at HttpRouter.getResponse (C:\snapshot\project\src\routers\HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:150:38)
    at IncomingMessage.<anonymous> (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:75:43)
    at IncomingMessage.emit (node:events:514:28)
[2024-03-10T11:41:20.186Z] error: 	TypeError: fullProfile.userbuilds.weaponBuilds[buildId].Items is not iterable
    at ProfileFixerService.checkForOrphanedModdedItems (C:\snapshot\project\src\services\ProfileFixerService.ts:898:77)
    at GameController.gameStart (C:\snapshot\project\src\controllers\GameController.ts:189:42)
    at GameCallbacks.gameStart (C:\snapshot\project\src\callbacks\GameCallbacks.ts:62:29)
    at RouteAction.action (C:\snapshot\project\src\routers\static\GameStaticRouter.ts:36:43)
    at GameStaticRouter.handleStatic (C:\snapshot\project\src\di\Router.ts:47:63)
    at HttpRouter.handleRoute (C:\snapshot\project\src\routers\HttpRouter.ts:79:62)
    at HttpRouter.getResponse (C:\snapshot\project\src\routers\HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:150:38)
    at IncomingMessage.<anonymous> (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:75:43)
    at IncomingMessage.emit (node:events:514:28)
```

*(Add a description of the issue here)*

## **How to reproduce**
1. Start Game
2. Create a preset
3. Logout
4. Log back in
5. Game shows mouse pointer on start screen / Server shows errors.

## **Log files**
Server: attached
BepinEx: attached
Client: attached

## **Profile**
profile is added
## Screenshots
no screenshots of value!

---
### Attachments
- [server-2024-03-10.log](https://dev.sp-tarkov.com/attachments/6a317790-a652-4420-9d91-b7e405e0b1a4) (74 KiB)
- [LogOutput.log](https://dev.sp-tarkov.com/attachments/b0bd17e5-d509-4a49-b021-6b8e98c5cf88) (9 KiB)
- [2024.03.10_11-35-22_0.14.1.1.28965 traces.log](https://dev.sp-tarkov.com/attachments/1182e58a-880b-4ecf-ab91-7a0607f576e7) (29 KiB)
- [65bfbc370004e2f7515b406b.zip](https://dev.sp-tarkov.com/attachments/621462a3-502d-4cb7-96ad-24ae50e19dad) (108 KiB)

---

[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/564) by _**ObiOne**_

**Comment by refringe** [comment]
Attached Profile

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/564#issuecomment-24533) by _**ObiOne**_

**Comment by refringe** [comment]
You need to zip the profile to attach it

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/564#issuecomment-24537) by _**chomp**_

**Comment by refringe** [comment]
Further investigation showed, it is a buggy preset from a GunSmith task. Unfortunately I overwrote the one, while investigating. :-(
For next time I know to zip the profile. Sorry....

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/564#issuecomment-24538) by _**ObiOne**_

**Comment by refringe** [comment]
Alright, I created a new preset, logged out, when I tried to log back in (Restart the server) the Game does not start and shows above error message again. So its 100% reproducable for me at the moment. I attached the new profile as zip! (y)

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/564#issuecomment-24555) by _**ObiOne**_

**Comment by refringe** [comment]
Seems like a profile editing issue. 3.8 has all of the captials at the start of the word and with editor it turns it back to lowercase.

	His			"id": "65eda6eb0100163fbf6b37ea",
				"name": "GunSmith6",
				"root": "20e14331ff85a77f46015221",
				"items": [
                
                
    Mine        "Id": "65ee192301001dfbecaf58a3",
				"Name": "ADAR",
				"Root": "5b1ea854c5df0ed6ca09a6f9",
				"Items": [
                
                

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/564#issuecomment-24556) by _**Kaeno**_

**Comment by refringe** [comment]
> @ObiOne Did you use Profile Editor to create this preset? I don't see any calls in your server log to the route the client would call for creating a preset

No the preset was only created ingame. The presets before were deleted using sublime editor. But no preset was created out of the game.
The profile is 100% created in SPT 3.8.0 and was not altered by me (except for deleting the presets, to do some bug-tracing).

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/564#issuecomment-24558) by _**ObiOne**_

**Comment by refringe** [comment]
Attached a screenshot of the version

---
### Attachments
- [Screenshot 2024-03-10 215741.png](https://dev.sp-tarkov.com/attachments/45362d41-4cec-48cd-b59a-d6510006bb26) (1310 KiB)


---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/564#issuecomment-24559) by _**ObiOne**_

**Comment by refringe** [comment]
Nobody has been able to reproduce this, closing

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/564#issuecomment-24860) by _**DrakiaXYZ**_
