### ISSUE TITLE
3.8.0 the problem with the intelligence center

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/server#413]
## **General information**
**Project issue is for:**
*3.8.0*

**Expected result**:
*transfer the crafted graphics card to the inventory.*

**Actual result**:
*it is not possible to transfer the crafted graphics card to the inventory. the process freezes and is interrupted after the end of time.*

*(Add a description of the issue here)*

## **How to reproduce**
1.start the process of making a graphic card in the intelligence center 
2.take the finished graphic card from the intelligence center to the inventory
3. 

## **Log files**
Server: *[2024-03-03T08:52:53.325Z] info: 	[Запрос Клиента] /client/game/profile/items/moving
[2024-03-03T08:52:53.332Z] error: 	TypeError: Cannot use 'in' operator to search for 'parentId' in 60391afc25aff57af81f7085
[2024-03-03T08:52:53.328Z] debug: 	event: HideoutTakeProduction
[2024-03-03T08:52:53.333Z] error: 	TypeError: Cannot use 'in' operator to search for 'parentId' in 60391afc25aff57af81f7085
[2024-03-03T08:52:53.334Z] error: 	TypeError: Cannot use 'in' operator to search for 'parentId' in 60391afc25aff57af81f7085
    at InventoryHelper.getInventoryItemHash (C:\snapshot\project\src\helpers\InventoryHelper.ts:940:19)
    at InventoryHelper.getItemSize (C:\snapshot\project\src\helpers\InventoryHelper.ts:723:70)
    at InventoryHelper.canPlaceItemInContainer (C:\snapshot\project\src\helpers\InventoryHelper.ts:288:31)
    at InventoryHelper.canPlaceItemsInInventory (C:\snapshot\project\src\helpers\InventoryHelper.ts:250:22)
    at HideoutController.handleRecipe (C:\snapshot\project\src\controllers\HideoutController.ts:948:35)
    at HideoutController.takeProduction (C:\snapshot\project\src\controllers\HideoutController.ts:765:18)
    at HideoutCallbacks.takeProduction (C:\snapshot\project\src\callbacks\HideoutCallbacks.ts:148:39)
    at HideoutItemEventRouter.handleItemEvent (C:\snapshot\project\src\routers\item_events\HideoutItemEventRouter.ts:62:46)
    at ItemEventRouter.handleEvents (C:\snapshot\project\src\routers\ItemEventRouter.ts:42:29)
    at ItemEventCallbacks.handleEvents (C:\snapshot\project\src\callbacks\ItemEventCallbacks.ts:26:52)
[2024-03-03T08:52:53.333Z] error: 	TypeError: Cannot use 'in' operator to search for 'parentId' in 60391afc25aff57af81f7085
    at InventoryHelper.getInventoryItemHash (C:\snapshot\project\src\helpers\InventoryHelper.ts:940:19)
    at InventoryHelper.getItemSize (C:\snapshot\project\src\helpers\InventoryHelper.ts:723:70)
    at InventoryHelper.canPlaceItemInContainer (C:\snapshot\project\src\helpers\InventoryHelper.ts:288:31)
    at InventoryHelper.canPlaceItemsInInventory (C:\snapshot\project\src\helpers\InventoryHelper.ts:250:22)
    at HideoutController.handleRecipe (C:\snapshot\project\src\controllers\HideoutController.ts:948:35)
    at HideoutController.takeProduction (C:\snapshot\project\src\controllers\HideoutController.ts:765:18)
    at HideoutCallbacks.takeProduction (C:\snapshot\project\src\callbacks\HideoutCallbacks.ts:148:39)
    at HideoutItemEventRouter.handleItemEvent (C:\snapshot\project\src\routers\item_events\HideoutItemEventRouter.ts:62:46)
    at ItemEventRouter.handleEvents (C:\snapshot\project\src\routers\ItemEventRouter.ts:42:29)
    at ItemEventCallbacks.handleEvents (C:\snapshot\project\src\callbacks\ItemEventCallbacks.ts:26:52)*
BepinEx: *(found in `/BepinEx/LogOutput.log`)*
Client: *(found in `/Logs/log_<date>_<version>/<date>_<version> traces.log`)*

## **Profile**
You can optionally include your game profile if you think it would help us reproduce the error easily *(found in `/user/profiles/xxxxxxxxxxxx.json`)*
The profile id can be found in the top left of the launcher.

## Screenshots
*(Optional, only add them if you think it adds value)*

## Notes - PLEASE READ!
***DO NOT INCLUDE THIS SECTION IN THE REPORT***
- Do not include any of the text written in parentheses and italics in your report *(example text - do not include me in the report!)*
- If you uploaded and attach the log files to the issue report, instead of using the codepaste, please remove the "Log Files" section as well.
- If you use the codepaste site please make sure the paste has a sufficiently long lifespan set, 24hrs is often not enough.
- You must be able to replicate the issue with a fresh profile, while running *<ins>no</ins>* mods.
- If you are using a profile from an older version of SPT-AKI, then please make a fresh profile and replicate the issue like above prior.
- You must upload *<ins>all</ins>* the required log files, even if you think they are useless.
- Failure to comply with *ANY* of the requirements may result in your issue being closed without further investigation.

---

[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/542) by _**Torm_Ozz**_

**Comment by refringe** [comment]
This was fixed in a recent zip update, the profile is broken and a new one will need to be created.

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/542#issuecomment-24165) by _**chomp**_
