### ISSUE TITLE
3.8.0 Tagged and cursed raid settings couse bot generation error

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/server#603]
1. Go Factory day
2. Select "Tagged and cursed" in game settings.

```
[2024-01-30T09:17:54.243Z] info: 	[Client Request] /client/game/bot/generate
[2024-01-30T09:17:54.541Z] error: 	TypeError: Cannot read properties of undefined (reading 'mod_reciever')
[2024-01-30T09:17:54.522Z] debug: 	Generated 30 marksman () easy bots
[2024-01-30T09:17:54.541Z] error: 	TypeError: Cannot read properties of undefined (reading 'mod_reciever')
[2024-01-30T09:17:54.541Z] error: 	TypeError: Cannot read properties of undefined (reading 'mod_reciever')
    at BotEquipmentModGenerator.shouldModBeSpawned (C:\snapshot\project\src\generators\BotEquipmentModGenerator.ts:704:75)
    at BotEquipmentModGenerator.generateModsForWeapon (C:\snapshot\project\src\generators\BotEquipmentModGenerator.ts:372:41)
    at BotWeaponGenerator.generateWeaponByTpl (C:\snapshot\project\src\generators\BotWeaponGenerator.ts:174:65)
    at BotWeaponGenerator.generateRandomWeapon (C:\snapshot\project\src\generators\BotWeaponGenerator.ts:85:21)
    at BotInventoryGenerator.addWeaponAndMagazinesToInventory (C:\snapshot\project\src\generators\BotInventoryGenerator.ts:515:57)
    at BotInventoryGenerator.generateAndAddWeaponsToBot (C:\snapshot\project\src\generators\BotInventoryGenerator.ts:456:22)
    at BotInventoryGenerator.generateInventory (C:\snapshot\project\src\generators\BotInventoryGenerator.ts:82:14)
    at BotGenerator.generateBot (C:\snapshot\project\src\generators\BotGenerator.ts:202:52)
    at BotGenerator.prepareAndGenerateBot (C:\snapshot\project\src\generators\BotGenerator.ts:118:20)
    at BotController.generateBotsFirstTime (C:\snapshot\project\src\controllers\BotController.ts:214:54)
```

---

[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/352) by _**Barlog_M**_

**Comment by refringe** [comment]
Fixed with: https://dev.sp-tarkov.com/SPT-AKI/Server/commit/c498efe18fa5d611f74779c43881303d74bb2c01

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/352#issuecomment-22217) by _**chomp**_

**Comment by refringe** [comment]
Don't see any errors. Looks fixed.

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/352#issuecomment-22241) by _**Barlog_M**_
