### ISSUE TITLE
3.8.0 - TypeError: Cannot read properties of undefined (reading 'conditions') daily quest

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/server#652]
## **General information**:

**Project issue is for:** </br>
Server (probably)

**Expected result**:</br>
Daily quest is removed after completion.

**Actual result**:</br>
Daily quest persists after completion, clicking on Accept doesn't do anything. Also some UI features break like accepting rewards from progression quests.

Per above and noticed undefined error in server console.

Restarting game and server fixed issue.

## **How to reproduce**:
1. Complete daily for Therapist (not sure if it affects others)
2. I finished a raid on woods too, only noticed the daily I finished before is still on UI.

Stacktrace:
TypeError: Cannot read properties of undefined (reading 'conditions')
TypeError: Cannot read properties of undefined (reading 'conditions')
    at QuestHelper.getQuestReadyForProfile (C:\snapshot\project\src\helpers\QuestHelper.ts:417:38)
    at QuestController.acceptRepeatableQuest (C:\snapshot\project\src\controllers\QuestController.ts:383:53)
    at QuestCallbacks.acceptQuest (C:\snapshot\project\src\callbacks\QuestCallbacks.ts:47:41)
    at QuestItemEventRouter.handleItemEvent (C:\snapshot\project\src\routers\item_events\QuestItemEventRouter.ts:41:44)
    at ItemEventRouter.handleEvents (C:\snapshot\project\src\routers\ItemEventRouter.ts:42:38)
    at ItemEventCallbacks.handleEvents (C:\snapshot\project\src\callbacks\ItemEventCallbacks.ts:26:52)
    at RouteAction.action (C:\snapshot\project\src\routers\static\ItemEventStaticRouter.ts:16:52)
    at ItemEventStaticRouter.handleStatic (C:\snapshot\project\src\di\Router.ts:50:63)
    at HttpRouter.handleRoute (C:\snapshot\project\src\routers\HttpRouter.ts:79:62)
    at HttpRouter.getResponse (C:\snapshot\project\src\routers\HttpRouter.ts:44:30)

---
### Attachments
- [server-2024-01-14.log](https://dev.sp-tarkov.com/attachments/2e1b5c44-1161-4576-a8a6-3a8ef577c0cb) (419 KiB)
- [2024.01.14_7-29-19_0.14.0.0.28375 traces.log](https://dev.sp-tarkov.com/attachments/1028fa1f-71d0-49d4-a363-da4aabeaf40a) (234 KiB)
- [LogOutput.log](https://dev.sp-tarkov.com/attachments/c067b789-1e96-420b-9af0-48d064dc1146) (67 KiB)

---

[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/303) by _**Platinum**_

**Comment by refringe** [comment]
On a side note, my attachments (logs) keep getting deleted from this post and I cant upload my profile json. Getting this notification on the site too:
JavaScript error: TypeError: ct[jt.uuid] is undefined (https://dev.sp-tarkov.com/assets/js/index.js?v=1.18.5 @ 96:1734). Open browser console to see more details.

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/303#issuecomment-21506) by _**Platinum**_

**Comment by refringe** [comment]
I'm having trouble reproducing the error.

For now, I've made the server show an error when it cant find a quest and made the following code not die when this event occurs: https://dev.sp-tarkov.com/SPT-AKI/Server/commit/41d491dd169cc5a40a91711248a30e0a6f19d723

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/303#issuecomment-21528) by _**chomp**_

**Comment by refringe** [comment]
Thanks Chomp, probably what I would've done too

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/303#issuecomment-21529) by _**Platinum**_

**Comment by refringe** [comment]
I ran into this today with a twist, here's the stacktrace:
```
[ERROR] 09:49:07 TypeError: Cannot read properties of undefined (reading 'Name')
TypeError: Cannot read properties of undefined (reading 'Name')
TypeError: Cannot read properties of undefined (reading 'Name')
    at RepeatableQuestGenerator.generateExplorationExitCondition (F:\SPTDev\Server\project\src\generators\RepeatableQuestGenerator.ts:851:28)
    at RepeatableQuestGenerator.generateExplorationQuest (F:\SPTDev\Server\project\src\generators\RepeatableQuestGenerator.ts:749:40)
    at RepeatableQuestGenerator.generateRepeatableQuest (F:\SPTDev\Server\project\src\generators\RepeatableQuestGenerator.ts:107:29)
    at RepeatableQuestController.getClientRepeatableQuests (F:\SPTDev\Server\project\src\controllers\RepeatableQuestController.ts:154:67)
    at QuestCallbacks.activityPeriods (F:\SPTDev\Server\project\src\callbacks\QuestCallbacks.ts:93:73)
    at RouteAction.action (F:\SPTDev\Server\project\src\routers\static\QuestStaticRouter.ts:20:48)
    at QuestStaticRouter.handleStatic (F:\SPTDev\Server\project\src\di\Router.ts:50:63)
    at HttpRouter.handleRoute (F:\SPTDev\Server\project\src\routers\HttpRouter.ts:79:62)
    at HttpRouter.getResponse (F:\SPTDev\Server\project\src\routers\HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (F:\SPTDev\Server\project\src\servers\http\AkiHttpListener.ts:150:38)
```
This was before SPT reached the main menu, it was probably retrieving the daily quests generated for the day. Created a new profile and the error did not repeat.

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/303#issuecomment-21702) by _**fatrat**_

**Comment by refringe** [comment]
> I ran into this today with a twist, here's the stacktrace:
> ```
> [ERROR] 09:49:07 TypeError: Cannot read properties of undefined (reading 'Name')
> TypeError: Cannot read properties of undefined (reading 'Name')
> TypeError: Cannot read properties of undefined (reading 'Name')
>     at RepeatableQuestGenerator.generateExplorationExitCondition (F:\SPTDev\Server\project\src\generators\RepeatableQuestGenerator.ts:851:28)
>     at RepeatableQuestGenerator.generateExplorationQuest (F:\SPTDev\Server\project\src\generators\RepeatableQuestGenerator.ts:749:40)
>     at RepeatableQuestGenerator.generateRepeatableQuest (F:\SPTDev\Server\project\src\generators\RepeatableQuestGenerator.ts:107:29)
>     at RepeatableQuestController.getClientRepeatableQuests (F:\SPTDev\Server\project\src\controllers\RepeatableQuestController.ts:154:67)
>     at QuestCallbacks.activityPeriods (F:\SPTDev\Server\project\src\callbacks\QuestCallbacks.ts:93:73)
>     at RouteAction.action (F:\SPTDev\Server\project\src\routers\static\QuestStaticRouter.ts:20:48)
>     at QuestStaticRouter.handleStatic (F:\SPTDev\Server\project\src\di\Router.ts:50:63)
>     at HttpRouter.handleRoute (F:\SPTDev\Server\project\src\routers\HttpRouter.ts:79:62)
>     at HttpRouter.getResponse (F:\SPTDev\Server\project\src\routers\HttpRouter.ts:44:30)
>     at AkiHttpListener.getResponse (F:\SPTDev\Server\project\src\servers\http\AkiHttpListener.ts:150:38)
> ```
> This was before SPT reached the main menu, it was probably retrieving the daily quests generated for the day. Created a new profile and the error did not repeat.

Likely resolved with: https://dev.sp-tarkov.com/SPT-AKI/Server/commit/727a85f5fcde80184eb50a734685436005770575

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/303#issuecomment-21709) by _**chomp**_
