### ISSUE TITLE
3.8.0 - TypeError: Cannot read properties of undefined when trying to save magazine preset

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/server#667]
## **General information**:

**Project issue is for:** </br>
Server

**Expected result**:</br>
Saving a magazine preset works

**Actual result**:</br>
On clicking save, nothing happens on the UI and an undefined error is produced. The preset UI becomes unresponsive and needs to be closed by Esc.

Using 3.8.0 commit 0e021d246f173b15bd61da49900c3758744d79e9

Steps to reproduce:
- Create new preset for 30rnd 5.45 mag
- Add 3x 5.45 BP at top
- Add 1x 5.45 BP in middle
- Try to save preset

Stacktrace (also in Server logs)

[2024-01-11T10:52:53.527Z] error: 	TypeError: Cannot read properties of undefined (reading 'findIndex')
    at BuildController.createMagazineTemplate (C:\snapshot\project\src\controllers\BuildController.ts:209:67)
    at BuildsCallbacks.createMagazineTemplate (C:\snapshot\project\src\callbacks\BuildsCallbacks.ts:36:30)
    at RouteAction.action (C:\snapshot\project\src\routers\static\BuildStaticRouter.ts:25:49)
    at BuildsStaticRouter.handleStatic (C:\snapshot\project\src\di\Router.ts:50:63)
    at HttpRouter.handleRoute (C:\snapshot\project\src\routers\HttpRouter.ts:79:62)
    at HttpRouter.getResponse (C:\snapshot\project\src\routers\HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:150:38)
    at IncomingMessage.<anonymous> (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:75:43)
    at IncomingMessage.emit (node:events:514:28)
    at endReadableNT (node:internal/streams/readable:1589:12)

---
### Attachments
- [server-2024-01-11.log](https://dev.sp-tarkov.com/attachments/edf56903-9a39-4125-b27f-2f7004d2a8f0) (385 KiB)
- [LogOutput.log](https://dev.sp-tarkov.com/attachments/3151094f-3ed7-401b-8899-4eaae99c7ae8) (97 KiB)
- [2024.01.11_10-21-57_0.14.0.0.28375 traces.log](https://dev.sp-tarkov.com/attachments/eb17773d-3da0-41bd-829c-9413ef6cd04a) (253 KiB)

---

[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/288) by _**Platinum**_

**Comment by refringe** [comment]
Should be fixed with: https://dev.sp-tarkov.com/SPT-AKI/Server/commit/3b255f3ce4a1456ec3fa6bc836621a8f119e874f

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/288#issuecomment-21368) by _**chomp**_
