### ISSUE TITLE
[3.7.3] Scav Run Through cause exception

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/server#759]
SPT-AKI 3.7.3 release. No Mods (removed all mods to check if issue in place)

1. Run factory.
2. Run to closest extract.
3. Get exception and unable to end raid.

```
[2023-11-24T01:48:01.128Z] error: 	TypeError: Cannot read properties of undefined (reading 'filter')
[2023-11-24T01:48:01.113Z] debug: 	Raid outcome: runner
[2023-11-24T01:48:01.129Z] error: 	TypeError: Cannot read properties of undefined (reading 'filter')
[2023-11-24T01:48:01.129Z] error: 	TypeError: Cannot read properties of undefined (reading 'filter')
    at InRaidHelper.updateScavProfileDataPostRaid (C:\snapshot\project\src\helpers\InRaidHelper.ts:243:56)
    at InraidController.savePlayerScavProgress (C:\snapshot\project\src\controllers\InraidController.ts:285:27)
    at InraidController.savePostRaidProgress (C:\snapshot\project\src\controllers\InraidController.ts:95:18)
    at InraidCallbacks.saveProgress (C:\snapshot\project\src\callbacks\InraidCallbacks.ts:44:31)
    at RouteAction.action (C:\snapshot\project\src\routers\static\InraidStaticRouter.ts:17:49)
    at InraidStaticRouter.handleStatic (C:\snapshot\project\src\di\Router.ts:50:63)
    at HttpRouter.handleRoute (C:\snapshot\project\src\routers\HttpRouter.ts:79:62)
    at HttpRouter.getResponse (C:\snapshot\project\src\routers\HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:150:38)
    at IncomingMessage.<anonymous> (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:75:43)
[2023-11-24T01:48:01.129Z] error: 	TypeError: Cannot read properties of undefined (reading 'filter')
    at InRaidHelper.updateScavProfileDataPostRaid (C:\snapshot\project\src\helpers\InRaidHelper.ts:243:56)
    at InraidController.savePlayerScavProgress (C:\snapshot\project\src\controllers\InraidController.ts:285:27)
    at InraidController.savePostRaidProgress (C:\snapshot\project\src\controllers\InraidController.ts:95:18)
    at InraidCallbacks.saveProgress (C:\snapshot\project\src\callbacks\InraidCallbacks.ts:44:31)
    at RouteAction.action (C:\snapshot\project\src\routers\static\InraidStaticRouter.ts:17:49)
    at InraidStaticRouter.handleStatic (C:\snapshot\project\src\di\Router.ts:50:63)
    at HttpRouter.handleRoute (C:\snapshot\project\src\routers\HttpRouter.ts:79:62)
    at HttpRouter.getResponse (C:\snapshot\project\src\routers\HttpRouter.ts:44:30)
    at AkiHttpListener.getResponse (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:150:38)
    at IncomingMessage.<anonymous> (C:\snapshot\project\src\servers\http\AkiHttpListener.ts:75:43)

```

---

[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/195) by _**Barlog_M**_

**Comment by refringe** [comment]
Can you attach your profile please

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/195#issuecomment-20481) by _**chomp**_

**Comment by refringe** [comment]
Sorry. Here is a profile https://codepaste.sp-tarkov.com/?3552f6a8b4760bc0#G1SEJqPHweJB67TvhAGS7hUGQTAUnhuSGvtxAj1x6PZS

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/195#issuecomment-20491) by _**Barlog_M**_

**Comment by refringe** [comment]
Fixed with: https://dev.sp-tarkov.com/SPT-AKI/Server/commit/40573019534009a70438ee1fcd5e2ff6097402e8

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/195#issuecomment-20493) by _**chomp**_
