### ISSUE TITLE
Scav repeatable quests can cause an error

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/server#765]
## **General information**:

**Project issue is for:** </br>
Server

**Expected result**:</br>
No error

**Actual result**:</br>
Sometimes scav runs throw an error:

```
[2023-11-19T23:27:44.820Z] error: 	TypeError: pmcData.RepeatableQuests is not iterable
    at QuestHelper.getQuestFromDb (C:\snapshot\project\src\helpers\QuestHelper.ts:674:50)
    at QuestHelper.applyQuestReward (C:\snapshot\project\src\helpers\QuestHelper.ts:753:33)
    at QuestHelper.failQuest (C:\snapshot\project\src\helpers\QuestHelper.ts:631:35)
    at InRaidHelper.processFailedQuests (C:\snapshot\project\src\helpers\InRaidHelper.ts:247:38)
    at InRaidHelper.updateProfileBaseStats (C:\snapshot\project\src\helpers\InRaidHelper.ts:186:14)
    at InraidController.savePlayerScavProgress (C:\snapshot\project\src\controllers\InraidController.ts:283:38)
    at InraidController.savePostRaidProgress (C:\snapshot\project\src\controllers\InraidController.ts:95:18)
    at InraidCallbacks.saveProgress (C:\snapshot\project\src\callbacks\InraidCallbacks.ts:44:31)
    at RouteAction.action (C:\snapshot\project\src\routers\static\InraidStaticRouter.ts:17:49)
    at InraidStaticRouter.handleStatic (C:\snapshot\project\src\di\Router.ts:50:63)
```

This is caused by the same issue as fixed in this commit, but for the scav profile:
https://dev.sp-tarkov.com/SPT-AKI/Server/commit/aeea8f6e49413c3bb49e21fd81bfea25e4295626

User support ticket in Discord is the source of this bug

## **How to reproduce**:
1. Do scav runs, apparently happens randomly

## **Log files**:
Server: https://codepaste.sp-tarkov.com/?66c3e8de24550c14#6hSgL31C3t8ZS1SqgCkhnLAyQvE5iTxX5T48e5Kzozk1

---

[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/189) by _**DrakiaXYZ**_

**Comment by refringe** [comment]
Im hoping its fixed with: https://dev.sp-tarkov.com/SPT-AKI/Server/commit/ddb9917c6b03cea4dc7d27f27d1c1b356f64edcd

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/189#issuecomment-20537) by _**chomp**_
