### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/server#909]
There's still an error!
Attempted to parse file: Aki_Data/Server/configs/playerscav.json. Error: Expected "[", "false", "null", "true", "{", number, or string but end of input found.
The application had a critical error and failed to run
Exception produced: Error: Cannot inject the dependency at position #1 of "Watermark" constructor. Reason:
    Attempted to parse file: Aki_Data/Server/configs/playerscav.json. Error: Expected "[", "false", "null", "true", "{", number, or string but end of input found.

Stacktrace:
 Error: Cannot inject the dependency at position #1 of "Watermark" constructor. Reason:
    Attempted to parse file: Aki_Data/Server/configs/playerscav.json. Error: Expected "[", "false", "null", "true", "{", number, or string but end of input found.
    at C:\snapshot\project\node_modules\tsyringe\dist\cjs\dependency-container.js:324:23
    at Array.map (<anonymous>)
    at C:\snapshot\project\node_modules\tsyringe\dist\cjs\dependency-container.js:295:38
    at InternalDependencyContainer.construct (C:\snapshot\project\node_modules\tsyringe\dist\cjs\dependency-container.js:297:11)
    at InternalDependencyContainer.resolveRegistration (C:\snapshot\project\node_modules\tsyringe\dist\cjs\dependency-container.js:166:51)
    at InternalDependencyContainer.resolve (C:\snapshot\project\node_modules\tsyringe\dist\cjs\dependency-container.js:109:33)
    at Program.start (C:\snapshot\project\obj\Program.js)
    at Object.<anonymous> (C:\snapshot\project\obj\ide\ReleaseEntry.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
Press Enter to close the window

---

[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/42) by _**zhongmof**_

**Comment by refringe** [comment]
Issue not filled out, closing

(You should reinstall SPT)

---
[Originally written](https://dev.sp-tarkov.com/SPT/Issues/issues/42#issuecomment-18349) by _**chomp**_
