### ISSUE TITLE
Unpack the "Opened case" item will throw exception

### ISSUE THREAD

**Issue by dounai2333** [sp-tarkov/server#996]
### SPT Version

3.10

### Project Type

Server

### Expected Result

Got reward with several "Sealed box" items and 1 or 2 "Contraband box" items.

### Actual Result

Server throw a exception and cause client softlock.

### Steps To Reproduce

1. Get "Opened case" item (tpl: 674078c4a9c9adf0450d59f9)
2. Unpack
3. Exception happens

### Server Log

```
TypeError: Cannot read properties of undefined (reading 'item')
TypeError: Cannot read properties of undefined (reading 'item')
    at WeightedRandomHelper.getWeightedValue (C:\snapshot\src\helpers\WeightedRandomHelper.ts:16:27)
    at LootGenerator.pickRewardItem (C:\snapshot\src\generators\LootGenerator.ts:627:46)
    at LootGenerator.getRandomLootContainerLoot (C:\snapshot\src\generators\LootGenerator.ts:599:46)
    at InventoryController.openRandomLootContainer (C:\snapshot\src\controllers\InventoryController.ts:825:52)
    at InventoryCallbacks.openRandomLootContainer (C:\snapshot\src\callbacks\InventoryCallbacks.ts:201:34)
    at InventoryItemEventRouter.handleItemEvent (C:\snapshot\src\routers\item_events\InventoryItemEventRouter.ts:89:48)
    at ItemEventRouter.handleEvents (C:\snapshot\src\routers\ItemEventRouter.ts:36:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ItemEventCallbacks.handleEvents (C:\snapshot\src\callbacks\ItemEventCallbacks.ts:22:31)
```

### BepinEx Log

None

### Client Log

None

### Screenshots

In commit https://github.com/sp-tarkov/server/commit/366276797295d52ddf0aee9b6e6dd5aa0f0b1953, "Opened case" has been added and have rewards, however the "Opened case" item use the wrong value:

https://github.com/sp-tarkov/server/blob/531dca5f92baa61aa522bdd0e977acd3ee3993dc/project/assets/configs/inventory.json#L1414

Fixes:
```
            "rewardTplPool": {
                "67409848d0b2f8eb9b034db9": 5,
                "67408903268737ef6908d432": 1
            }
```

**Comment by chompDev** [comment]
Fixed with: https://github.com/sp-tarkov/server/commit/c6a9a1afb5b43463fdfa57feb18277c67b2b3334
